version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
      args:
        - UID=${UID}
    image: docker-boilerplate
    command: sh .docker/scripts/run.sh
    volumes:
      - ./:/home/node/app

